### ISSUE TITLE
Switch to php7.0-cgi instead of php7.0?

### ISSUE THREAD

**Issue by piotr-szegda** [GM-Script-Writer-62850/Ubuntu-Mainline-Kernel-Updater#28]
Maybe it would be better to install php7.0-cgi instead of php7.0 becouse it's not depend on apache2?

**Comment by GM-Script-Writer-62850** [comment]
then why not php7-cli?

**Comment by piotr-szegda** [comment]
Maybe it's will be even better but I am almost sure that php7.0 it's not best solution because it's depend on apache2.

**Comment by GM-Script-Writer-62850** [comment]
i guess you missed my edit? do you want to use lighttpd instead of apache2 and if so why?
currently i consider apache2 a requirement

**Comment by piotr-szegda** [comment]
To be honest I don't understand why any http server is required to this script if it's working without?

**Comment by GM-Script-Writer-62850** [comment]
so you are saying if you remove apache2 you can still use the gui in your web browser? i do not see how that is possible without either apache2 or lighttpd having a running instance

**Comment by piotr-szegda** [comment]
This script have web GUI? I don't see anything about it in readme.

**Comment by GM-Script-Writer-62850** [comment]
wait a minute ![facepam](http://i2.kym-cdn.com/entries/icons/facebook/000/000/554/facepalm.jpg)
I failed to read which project this issue is under, i was thinking this was under https://github.com/GM-Script-Writer-62850/PHP-Scanner-Server

Now that we have that issue straitened out (sorry about that)
i thought i have php-cli defined in this project, ill look into it

**Comment by GM-Script-Writer-62850** [comment]
See commit  2d65851

**Comment by piotr-szegda** [comment]
Everyone makes mistakes :) Thank you.
